name: redit_tutorial
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0-374.1.beta <3.0.0"

dependencies:
  cloud_firestore: ^4.1.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.1.4
  firebase_core: ^2.3.0
  firebase_storage: ^11.0.6
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.1
  fpdart: ^0.3.0
  google_sign_in: ^5.4.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
