// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1PZ43gfKF8gPDRtyRhvoaqbdpeOAnYu4',
    appId: '1:924607572467:web:7d649b6b7bac5a2b8a8a86',
    messagingSenderId: '924607572467',
    projectId: 'reddit-clone-479fe',
    authDomain: 'reddit-clone-479fe.firebaseapp.com',
    storageBucket: 'reddit-clone-479fe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB06_W7azYGGSriXCQ8fYpmXzujDXnRVqc',
    appId: '1:924607572467:android:de2fd4b554ddc4258a8a86',
    messagingSenderId: '924607572467',
    projectId: 'reddit-clone-479fe',
    storageBucket: 'reddit-clone-479fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkhzCGFF-HtMvX2t0Llgqd93Ea1HRA4W0',
    appId: '1:924607572467:ios:99712a8a3a4023d98a8a86',
    messagingSenderId: '924607572467',
    projectId: 'reddit-clone-479fe',
    storageBucket: 'reddit-clone-479fe.appspot.com',
    iosClientId: '924607572467-baribm52ssijtraa91n02kc653pib0ma.apps.googleusercontent.com',
    iosBundleId: 'com.example.reditTutorial',
  );
}
